"""Markdown report — the version people read in a PR, a wiki or on GitHub."""

from __future__ import annotations

from typing import Dict, List, Sequence

from repograph_core.model import ScanResult


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]], limit: int = 200) -> str:
    if not rows:
        return "_none_\n"
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows[:limit]:
        cells = [str(c).replace("|", "\\|").replace("\n", " ") for c in row]
        out.append("| " + " | ".join(cells) + " |")
    if len(rows) > limit:
        out.append(f"| … | {len(rows) - limit} more rows omitted |" + " |" * (len(headers) - 2))
    return "\n".join(out) + "\n"


def _mermaid(source: str) -> str:
    return f"```mermaid\n{source}\n```\n"


def render(result: ScanResult, mermaid: Dict[str, str]) -> str:
    meta = result.meta
    metrics = result.metrics
    summary = result.summary
    lines: List[str] = []
    add = lines.append

    add(f"# {meta.repo_name} — architecture report\n")
    add(f"> Generated by **repograph {meta.version}** on {meta.generated_at} from `{meta.root}`. "
        f"Static analysis only — no AI, no code execution"
        f"{', OSV advisory lookup enabled' if meta.online else ', offline (no advisory lookup)'}.\n")

    add("## 1. What this is\n")
    add(f"{summary.get('purpose', '')}\n")
    add(f"- **Shape:** {summary.get('shape', 'unknown')}")
    add(f"- **Primary languages:** {', '.join(summary.get('primary_languages', [])) or 'unknown'}")
    add(f"- **Architecture style(s):** {', '.join(summary.get('architecture_styles', [])) or 'unclassified'}")
    add(f"- **Risk level:** {summary.get('risk_level', 'unknown')} "
        f"(score {summary.get('risk_score', 0)})")
    add(f"- **Size:** {metrics.scanned_files} files · {metrics.loc:,} lines · "
        f"{metrics.apps} application(s) · {metrics.components} components\n")

    if result.git.is_repo:
        add(f"- **History:** {result.git.commits} commits by {result.git.contributors} "
            f"contributor(s), {result.git.first_commit} → {result.git.last_commit}\n")

    business = result.business or {}
    if business:
        add("## 1b. In plain language\n")
        add(f"{business.get('what_it_is', '')}\n")
        for label, key in (("What it lets people do", "capabilities"),
                           ("Where its data lives", "data"),
                           ("What it depends on", "dependencies"),
                           ("What could hurt", "risks")):
            points = business.get(key) or []
            if not points:
                continue
            add(f"**{label}**\n")
            for point in points[:6]:
                add(f"- **{point.get('title', '')}** — {point.get('plain', '')}")
            add("")
        add("_The full plain-language version is in `BUSINESS-OVERVIEW.md`._\n")

    add("## 2. Applications\n")
    add(_table(
        ["Application", "Kind", "Root", "Languages", "Frameworks", "Files", "LOC", "Style"],
        [[a.name, a.kind, f"`{a.root or '.'}`", ", ".join(a.languages[:3]),
          ", ".join(a.frameworks[:3]), str(a.files), f"{a.loc:,}", a.architecture_style]
         for a in result.apps]))
    for app in result.apps:
        if app.description:
            add(f"**{app.name}** — {app.description}\n")
        if app.purpose and app.purpose != app.description:
            add(f"> Read from the code: {app.purpose}\n")

    add("## 3. Architecture diagrams\n")
    add("### System context (C4 level 1)\n")
    add(_mermaid(mermaid.get("c4-context", "")))
    add("### Containers (C4 level 2)\n")
    add(_mermaid(mermaid.get("c4-container", "")))
    add("### Application and external dependencies\n")
    add(_mermaid(mermaid.get("application-dependencies", "")))
    add("### Component dependency graph\n")
    add(_mermaid(mermaid.get("dependency-graph", "")))
    add("### Repository mindmap\n")
    add(_mermaid(mermaid.get("mindmap", "")))

    if result.flows:
        add("## 4. Process flows\n")
        for flow in result.flows[:10]:
            add(f"### {flow.name}\n")
            add(f"{flow.description}\n")
            key = f"flow-{flow.id}"
            if key in mermaid:
                add(_mermaid(mermaid[key]))

    add("## 5. API surface\n")
    add(f"{len(result.endpoints)} entrypoint(s) detected.\n")
    add(_table(["Kind", "Method", "Path", "Handler", "Framework", "Source"],
               [[e.kind, e.method, f"`{e.path}`", e.handler or "—", e.framework or "—",
                 f"`{e.file}:{e.line}`"] for e in result.endpoints], limit=150))

    add("## 6. External systems and integrations\n")
    add(_table(["System", "Kind", "Technology", "Used by", "Evidence"],
               [[s.name, s.kind, s.technology, ", ".join(s.apps) or "—",
                 f"`{s.evidence[0].file}:{s.evidence[0].line}`" if s.evidence else "—"]
                for s in result.external_systems]))

    add("## 7. Dependencies\n")
    by_ecosystem: Dict[str, int] = {}
    for dep in result.dependencies:
        by_ecosystem[dep.ecosystem] = by_ecosystem.get(dep.ecosystem, 0) + 1
    add(", ".join(f"**{k}**: {v}" for k, v in sorted(by_ecosystem.items())) or "_none_")
    add("")
    missing = [f for f in result.findings if f.identifier == "RG-DEP-MISSING"]
    if missing:
        add(f"### Missing declarations ({len(missing)})\n")
        add(_table(["Package", "First seen in"], [[f.package, f"`{f.file}`"] for f in missing]))
    unused = [f for f in result.findings if f.identifier == "RG-DEP-UNUSED"]
    if unused:
        add(f"### Declared but never imported ({len(unused)})\n")
        add(", ".join(f"`{f.package}`" for f in unused[:60]) + "\n")
    add("### Direct dependencies\n")
    add(_table(["Package", "Version", "Ecosystem", "Scope", "Used"],
               [[d.name, d.version or "—", d.ecosystem, d.scope, "yes" if d.used else "no"]
                for d in result.dependencies if d.direct], limit=200))

    add("## 8. Vulnerabilities and risks\n")
    counts = metrics.findings_by_severity
    add(" · ".join(f"**{k}**: {v}" for k, v in counts.items()) or "_no findings_")
    add("")
    if "findings-pie" in mermaid:
        add(_mermaid(mermaid["findings-pie"]))
    for severity in ("critical", "high", "medium", "low", "info"):
        items = [f for f in result.findings if f.severity == severity]
        if not items:
            continue
        add(f"### {severity.title()} ({len(items)})\n")
        add(_table(["Finding", "Where", "Id", "CWE", "Fix"],
                   [[f.title, f"`{f.file}:{f.line}`" if f.file else "—", f.identifier or "—",
                     f.cwe or "—", f.remediation] for f in items], limit=80))

    add("## 9. Infrastructure\n")
    infra = result.infrastructure or {}
    if infra.get("containers"):
        add("### Compose services\n")
        add(_table(["Service", "Image / build", "Ports", "Depends on"],
                   [[c.get("name"), c.get("image") or c.get("build", ""),
                     ", ".join(c.get("ports", [])), ", ".join(c.get("depends_on", []))]
                    for c in infra["containers"]]))
    if infra.get("dockerfiles"):
        add("### Dockerfiles\n")
        add(_table(["File", "Base images", "Ports", "User", "Multi-stage"],
                   [[f"`{d.get('file')}`", ", ".join(d.get("base_images", [])),
                     ", ".join(str(p) for p in d.get("ports", [])), d.get("user"),
                     "yes" if d.get("multistage") else "no"] for d in infra["dockerfiles"]]))
    if infra.get("kubernetes"):
        add("### Kubernetes\n")
        add(_table(["Kind", "Name", "Images"],
                   [[k.get("kind"), k.get("name"), ", ".join(k.get("images", []))]
                    for k in infra["kubernetes"]]))
    if infra.get("terraform"):
        add("### Terraform\n")
        add(_table(["Block", "Type", "Name", "File"],
                   [[t.get("block"), t.get("type"), t.get("name"), f"`{t.get('file')}`"]
                    for t in infra["terraform"]]))
    if infra.get("ci"):
        add("### CI / CD\n")
        add(_table(["System", "Pipeline", "Triggers", "Jobs"],
                   [[c.get("system"), c.get("name"), ", ".join(c.get("triggers", [])),
                     ", ".join(str(j.get("name")) for j in (c.get("jobs") or [])[:10])]
                    for c in infra["ci"]]))

    add("## 10. Quality signals\n")
    add(f"- Test files: {metrics.test_files} ({metrics.test_ratio:.0%} of source files)")
    add(f"- Documentation files: {metrics.doc_files}")
    add(f"- Dependency cycles between components: {metrics.cycles}")
    add(f"- Largest fan-in: {metrics.max_component_fan_in} · largest fan-out: {metrics.max_component_fan_out}")
    add(f"- Unresolved imports: {summary.get('unresolved_imports', 0)}\n")
    if result.cycles:
        names = {c.id: c.name for c in result.components}
        add("### Cycles\n")
        for cycle in result.cycles[:20]:
            add(f"- {' → '.join(names.get(n, n) for n in cycle)}")
        add("")
    if result.git.hotspots:
        add("### Change hotspots\n")
        add(_table(["File", "Commits"],
                   [[f"`{h.get('file')}`", str(h.get("changes"))] for h in result.git.hotspots], limit=25))

    if result.ai.present:
        ai = result.ai
        add("## 11. Model contributions\n")
        add(f"> Written by **{ai.provenance.tool} {ai.provenance.model}** on "
            f"{ai.provenance.generated_at}, validated against the scan. This section is "
            f"judgement, not measurement — everything above it is machine-derived.\n")
        for app in result.apps:
            if app.ai_summary:
                add(f"**{app.name}** — {app.ai_summary}\n")
                for item in app.ai_responsibilities:
                    add(f"- {item}")
                if app.ai_responsibilities:
                    add("")
        if ai.insights:
            add(_table(["Kind", "Severity", "Insight", "Evidence"],
                       [[i.kind, i.severity, f"**{i.title}** — {i.detail}",
                         ", ".join(f"`{x}`" for x in i.evidence)] for i in ai.insights]))
        assessed = [f for f in result.findings if f.ai_assessment]
        if assessed:
            add("### Finding assessments\n")
            add(_table(["Finding", "Assessment", "Reasoning"],
                       [[f.title, f.ai_assessment, f.ai_reasoning] for f in assessed]))
        if ai.rejected:
            add(f"_{len(ai.rejected)} contribution(s) were rejected on merge._\n")

    if meta.warnings:
        add("## 12. Scan notes\n")
        for warning in meta.warnings:
            add(f"- {warning}")
        add("")
    add(f"\n---\n_Scanned {metrics.scanned_files} files in {metrics.duration_seconds}s._\n")
    return "\n".join(lines)
